#184995818 buyer to retrieve all items on available products
atlp-rwanda/e-comm-team-brogrammers-fn pull request #22
Opened 2023-04-24 13:33 UTC by Martha-Iradukunda

#### What does this PR do?
* This PR introduces the functionality for buyers to retrieve a list of all items available for purchase in the e-commerce brogrammersMall application.

#### Description of Task to be completed?
* The task to be completed is to implement a feature that allows buyers to view a list of all items available for purchase on the brogrammersMall app. This list should be comprehensive and up-to-date, reflecting all available products in the system.

#### How should this be manually tested?
* The feature can be manually tested by accessing the brogrammersMall app and verifying that the list of available products can be displayed on the screen. The list should contain all products available for purchase, and the information displayed should be accurate and up-to-date.

#### Any background context you want to provide?
* This feature is a crucial part of any e-commerce app, as it allows buyers to easily browse and select products they are interested in purchasing. The list of available products should be easy to access and navigate, with clear information on each product, including its name, description, price, and any other relevant details. Additionally, it is important to ensure that the list of available products is regularly updated to reflect any changes to the inventory.

#### What are the relevant pivotal tracker/Trello stories?
* [#184995818](https://www.pivotaltracker.com/n/projects/2639400/stories/184995818)

#### Screenshots (if appropriate)
![Screenshot from 2023-05-01 18-29-50](https://user-images.githubusercontent.com/101427855/235477838-a3b19141-f363-4539-9a17-72e51d9e448e.png)
![Screenshot from 2023-05-02 19-52-28](https://user-images.githubusercontent.com/101427855/235733832-d5d7bb8d-bfff-4cbd-8c9f-31651a56d274.png)

#### Questions:
N/A

2023-04-26 16:42 UTC, Zeden12 approved these changes
LGTM

2023-04-26 16:48 UTC, blackd44 approved these changes

2023-04-26 16:52 UTC, INValentin approved these changes
LGTM

2023-04-28 15:20 UTC, bencyubahiro77 approved these changes

2023-05-04 14:37 UTC, Patienceineza requested changes
Please paginate your end point get all products nedds to be pagination for sure

2023-05-04 17:07 UTC, Patienceineza approved these changes

2023-05-05 10:06 UTC, merged