Users should be able to turn on/off MFA
atlp-rwanda/e-comm-team-brogrammers-fn pull request #36
Opened 2023-05-03 11:22 UTC by INValentin

#### What does this PR do?
This PR provides the ability for users to increase level of security by enabling MFA for their accounts.
#### Description of Task to be completed?

Users that require a higher level of security (Sellers) should be able to turn on 2FA where authentication to the application also includes a an extra factor i.e SMS or Authentications codes. 
After a successful login, Sellers should be redirected to their dashboard

#### How should this be manually tested?
**To test this: **
- Login as usual
- Go to `/settings`
- Click Enable MFA button to enable MFA
- Logout
- When logging in again you will be asked to provide MFA code
- Enter the code from email, and hit verify. 
- You should be logged in.
#### Any background context you want to provide?
n/a
#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2639400/stories/184948160
#### Screenshots (if appropriate)

#### Questions:
n/a

2023-05-11 08:32 UTC, UmuhireJessie requested changes
Good work!

1. Add screenshots 
2. After enabling MFA (the toggle), how can you know the MFA is enabled? The toggle goes back to inactive

Right now, you can't know whether I have enabled it or not
![image](https://github.com/atlp-rwanda/e-comm-team-brogrammers-fn/assets/86103578/e958c78f-4a06-4f40-9ab4-00f68670bb3d)

2023-05-11 08:53 UTC, INValentin commented
I will add screenshots, about knowing whether MFA is already enabled, that's why I have a corresponding backend PR that will make that happen.

2023-05-15 17:21 UTC, blackd44 approved these changes

2023-05-15 19:10 UTC, edwinnambaje approved these changes

2023-05-15 20:05 UTC, UmuhireJessie approved these changes

2023-05-15 20:05 UTC, merged