#184948173 user can view notitifications
atlp-rwanda/e-comm-team-brogrammers-fn pull request #49
Opened 2023-05-18 17:08 UTC by INValentin

#### What does this PR do?
This PR enables users to view their notifications, and mark them as read/unread.

#### Description of Task to be completed?

The notifications pane should open up when a user clicks on the icon. It should contain a list of notifications as denoted in the mock up.

#### How should this be manually tested?
The notifications pane should open up when a user clicks on the icon. It should contain a list of notifications as denoted in the mock up.

You need to click the notification bell icon

#### Any background context you want to provide?
n/a
#### What are the relevant pivotal tracker/Trello stories?
https://www.pivotaltracker.com/n/projects/2639400/stories/184948173
#### Screenshots (if appropriate)
<img width="972" alt="Screenshot 2023-05-18 at 19 05 00" src="https://github.com/atlp-rwanda/e-comm-team-brogrammers-fn/assets/57767759/57aa33c9-02cb-4317-84e2-40719758aa39">

#### Questions:
n/a

2023-05-19 09:00 UTC, UmuhireJessie requested changes
Reduce the font-weight of this number
![image](https://github.com/atlp-rwanda/e-comm-team-brogrammers-fn/assets/86103578/e0b3d543-c7b1-49d5-8bea-8a6234e1a763)

2023-05-19 09:00 UTC, UmuhireJessie requested changes
Reduce the font-weight of this number
![image](https://github.com/atlp-rwanda/e-comm-team-brogrammers-fn/assets/86103578/e0b3d543-c7b1-49d5-8bea-8a6234e1a763)

2023-05-19 20:32 UTC, blackd44 approved these changes

2023-05-22 11:24 UTC, Habihirwe approved these changes
LGMT

2023-05-22 12:47 UTC, edwinnambaje approved these changes

2023-05-22 16:20 UTC, bencyubahiro77 approved these changes

2023-05-22 17:13 UTC, UmuhireJessie approved these changes

2023-05-22 17:13 UTC, merged