#185239763 Logging Feature
atlp-rwanda/e-comm-team-brogrammers-fn pull request #54
Opened 2023-05-26 11:41 UTC by Zeden12

#### What does this PR do?

this PR is to let Admin be able to get the logs feature on the website to track user actions and system events

#### Description of Task to be completed?

 This will help an Admin to monitor and troubleshoot any issues that may arise on the website easily. 

#### How should this be manually tested?

Logging as an admin navigate to the `admin dashboard` and click to `Activity Logs` you'll be able to see all logs

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker/Trello stories?

https://www.pivotaltracker.com/story/show/185239763

#### Screenshots (if appropriate)

<img width="1435" alt="Screen Shot 2023-05-26 at 13 37 02" src="https://github.com/atlp-rwanda/e-comm-team-brogrammers-fn/assets/118928495/44c73d7f-ab32-4538-b94b-a63e908c3696">

#### Questions:

N/A

2023-05-29 20:10 UTC, Martha-Iradukunda approved these changes

2023-05-29 21:28 UTC, Habihirwe approved these changes
LGMT

2023-05-29 21:46 UTC, edwinnambaje approved these changes

2023-05-30 06:20 UTC, blackd44 approved these changes
Looks good

2023-05-30 09:23 UTC, UmuhireJessie requested changes
Good work @Zeden12,
Please work on this:
![image](https://github.com/atlp-rwanda/e-comm-team-brogrammers-fn/assets/86103578/62b88ba1-6b95-4a6d-abcd-bbdffa35465c)

2023-05-30 11:52 UTC, bencyubahiro77 approved these changes

2023-05-30 12:24 UTC, UmuhireJessie approved these changes

2023-05-30 12:24 UTC, merged