#184948154 Setup GitHub Actions to run tests
atlp-rwanda/e-comm-team-brogrammers-fn pull request #6
Opened 2023-04-18 16:56 UTC by Zeden12

#### What does this PR do?

this PR is to set up github actions to run test on push and pull requests on this repo

#### Description of Task to be completed?

is to setup github workflow to run tests and Add a coverage Badge in Readme

#### How should this be manually tested?

clone the `repo`
create your branch 
push the codes and make a PR it will run the test automatically and update badge on readme file with test percentage

#### Any background context you want to provide?

n/a

#### What are the relevant pivotal tracker/Trello stories?

https://www.pivotaltracker.com/story/show/184948154

#### Screenshots (if appropriate)

N/A

#### Questions:

2023-04-20 09:09 UTC, Habihirwe approved these changes

2023-04-20 11:30 UTC, UmuhireJessie approved these changes
See why we have coverage as unknown yet have tests on `develop`

2023-04-20 11:31 UTC, UmuhireJessie requested changes
See comment

2023-04-21 12:23 UTC, edwinnambaje requested changes
you pushed your .env can you add it to .gitignore

2023-04-21 18:21 UTC, edwinnambaje approved these changes

2023-04-24 06:26 UTC, UmuhireJessie approved these changes

2023-04-24 06:27 UTC, merged